// <auto-generated />
using System;
using FinSteady_API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinSteady_API.Migrations
{
    [DbContext(typeof(SmartSaverDatabaseContext))]
    [Migration("20260917193814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinSteady_API.Infrastructure.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CardId"));

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("SavingBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("CardId")
                        .HasName("PK__Card__55FECDAE1FCE8F4F");

                    b.HasIndex("UserId");

                    b.ToTable("Card", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0B7045B95C");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.SavingGoal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoalId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("FundBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SavingRuleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GoalId")
                        .HasName("PK__Saving_G__8A4FFFD11414036C");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SavingRuleId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TargetDate" }, "idx_Saving_Goal_TargetDate");

                    b.ToTable("Saving_Goal", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.SavingRule", b =>
                {
                    b.Property<int>("SavingRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavingRuleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Rulename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("rulename");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SavingRuleId")
                        .HasName("PK__Saving_R__4050F25DE7C1E185");

                    b.ToTable("Saving_Rule", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A6BD830D540");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.HasIndex(new[] { "Date" }, "idx_Transaction_Date");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Kycdoc")
                        .HasColumnType("text")
                        .HasColumnName("KYCDoc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CA1835B49");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105347001A560")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "idx_User_Email");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.Card", b =>
                {
                    b.HasOne("FinSteady_API.Infrastructure.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Card__UserId__52593CB8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.SavingGoal", b =>
                {
                    b.HasOne("FinSteady_API.Infrastructure.Category", "Category")
                        .WithMany("SavingGoals")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Saving_Go__Categ__656C112C");

                    b.HasOne("FinSteady_API.Infrastructure.SavingRule", "SavingRule")
                        .WithMany("SavingGoals")
                        .HasForeignKey("SavingRuleId")
                        .HasConstraintName("FK__Saving_Go__Savin__66603565");

                    b.HasOne("FinSteady_API.Infrastructure.User", "User")
                        .WithMany("SavingGoals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Saving_Go__UserI__6477ECF3");

                    b.Navigation("Category");

                    b.Navigation("SavingRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.Transaction", b =>
                {
                    b.HasOne("FinSteady_API.Infrastructure.User", "FromUser")
                        .WithMany("TransactionFromUsers")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FK__Transacti__FromU__571DF1D5");

                    b.HasOne("FinSteady_API.Infrastructure.User", "ToUser")
                        .WithMany("TransactionToUsers")
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FK__Transacti__ToUse__5812160E");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.Category", b =>
                {
                    b.Navigation("SavingGoals");
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.SavingRule", b =>
                {
                    b.Navigation("SavingGoals");
                });

            modelBuilder.Entity("FinSteady_API.Infrastructure.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("SavingGoals");

                    b.Navigation("TransactionFromUsers");

                    b.Navigation("TransactionToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
